function [robot_pose_plus, robot_pose_minus ] = triangulation_forwardscut(a, b, rpa, rpb)
    xa = a(1);
    ya = a(2);
    xb = b(1);
    yb = b(2);
    rap = mod(rpa + pi,2*pi);
    rbp = mod(rpb + pi,2*pi);
    ab = sqrt((yb - ya)^2 + (xb - xa)^2);
    rab = atan2((yb - ya), (xb - xa));
    rba = mod(rab + pi,2*pi);
    alpha_angle = abs(rap - rab);
    beta_angle = abs(rba - rbp);
    ap = ab * (sin(beta_angle)/sin(alpha_angle + beta_angle));
    x_p = xa + ap * cos(rap);
    y_p = ya + ap * sin(rap);
    robot_pose_plus = [x_p;y_p];
    x_m = xa - ap * cos(rpa);
    y_m = ya - ap * sin(rpa);
    robot_pose_minus = [x_m;y_m];
